FORMAT: 1A
HOST: https://kogi-challenge.herokuapp.com/

# KOGI api

Simple test API for KOGI backend position allowing users to sign up, log in, add contacts and retrieve contacts.

## USER Collection [/questions]

### Create a new User access token for kogi-backend app [POST /users/auth]

+ Request (application/json)

    + Attributes (UserLocalAuth)

+ Response 201 (application/json)

    + Body

            {
                "user": {
                    "__v": 0,
                    "email": "a3barradas@gmail.com",
                    "firstName": "andres",
                    "lastName": "barradas",
                    "_id": "5948a9606ecf463d301e1d20",
                    "lastLoginAt": "2017-06-20T04:49:36.134Z",
                    "createdAt": "2017-06-20T04:49:36.134Z",
                    "password": "S5Nzmdv5LFt6BO2mmOFp2+xl4YOkc1sHmVzcR6SNcyQ="
                },
                "token": "38eede9e24eb30649178900427e77c37"
            }

+ Response 400 (application/json)

    + Body

                {
                    "user": false,
                    "token": "8e5834566ecafb64c495d08deccfde32"
                }


### Create a new User kogi-backend app [POST /users]

+ Request (application/json)

    + Attributes (UserColletion)

+ Response 201 (application/json)

    + Body

            {
                "user": {
                    "__v": 0,
                    "email": "a3barradas@gmail.com",
                    "firstName": "andres",
                    "lastName": "barradas",
                    "_id": "5948a9606ecf463d301e1d20",
                    "lastLoginAt": "2017-06-20T04:49:36.134Z",
                    "createdAt": "2017-06-20T04:49:36.134Z",
                    "password": "S5Nzmdv5LFt6BO2mmOFp2+xl4YOkc1sHmVzcR6SNcyQ="
                },
                "token": "38eede9e24eb30649178900427e77c37"
            }

+ Response 400 (application/json)

    + Body

                    {
                        "code": 4409,
                        "description": "E11000 duplicate key error collection: KOGI.users index: email_1 dup key: { : \"a3barradas@gmail.com\" }",
                        "userMessage": "The email is already in use"
                    }

### Create a new contact for current user [POST /users/me/contacts]

+ Request (application/json)

    + Attributes (ContactData)
    + Headers

            Authorization: Bearer 1af2a706fb133bf7f8f928671f844b65

+ Response 201 (application/json)

    + Body

            {
                "user": {
                    "_id": "5948adb51f4f7941cefd065b",
                    "email": "a3barradas@gmail.com",
                    "firstName": "andres",
                    "lastName": "barradas",
                    "__v": 0,
                    "lastLoginAt": "2017-06-20T05:09:39.222Z",
                    "createdAt": "2017-06-20T05:08:05.893Z",
                    "password": "S5Nzmdv5LFt6BO2mmOFp2+xl4YOkc1sHmVzcR6SNcyQ="
                },
                "firebaseContact": "hello@kogi.com"
            }

+ Response 409 (application/json)

    + Body

                {
                    "code": 4409,
                    "userMessage": "Cannot include an already included contact"
                }



### Create a new contact for a user [POST /users/:id/contacts]

+ Request (application/json)

    + Attributes (ContactData)
    + Headers

            Authorization: Bearer 1af2a706fb133bf7f8f928671f844b65


+ Response 201 (application/json)

    + Body

            {
                "user": {
                    "_id": "5948adb51f4f7941cefd065b",
                    "email": "a3barradas@gmail.com",
                    "firstName": "andres",
                    "lastName": "barradas",
                    "__v": 0,
                    "lastLoginAt": "2017-06-20T05:09:39.222Z",
                    "createdAt": "2017-06-20T05:08:05.893Z",
                    "password": "S5Nzmdv5LFt6BO2mmOFp2+xl4YOkc1sHmVzcR6SNcyQ="
                },
                "firebaseContact": "hello@kogi.com"
            }

+ Response 409 (application/json)

    + Body

                {
                    "code": 4409,
                    "userMessage": "Cannot include an already included contact"
                }


### Retrieve current user contacts [GET /users/me/contacts]

+ Request (application/json)

    + Attributes (ContactData
    + Headers

            Authorization: Bearer 1af2a706fb133bf7f8f928671f844b65


+ Response 201 (application/json)

    + Body

            {
                "user": {
                    "_id": "5948adb51f4f7941cefd065b",
                    "email": "a3barradas@gmail.com",
                    "firstName": "andres",
                    "lastName": "barradas",
                    "__v": 0,
                    "lastLoginAt": "2017-06-20T05:09:39.222Z",
                    "createdAt": "2017-06-20T05:08:05.893Z",
                    "password": "S5Nzmdv5LFt6BO2mmOFp2+xl4YOkc1sHmVzcR6SNcyQ="
                },
                "contacts": [
                    "hello@kogi.com",
                    "hello@kogi2.com",
                    "hello@kogi3.com"
                ]
            }

+ Response 409 (application/json)

    + Body

                {
                    "code": "4409",
                    "description": "any description message",
                    "userMessage": "error retrieving user contacts",
                }

### Retrieve an user contacts [GET /users/:id/contacts]

+ Request (application/json)

    + Attributes (ContactData
    + Headers

            Authorization: Bearer 1af2a706fb133bf7f8f928671f844b65


+ Response 201 (application/json)

    + Body

    [
        "hello@kogi.com",
        "hello@kogi2.com",
        "hello@kogi3.com"
    ]

+ Response 409 (application/json)

    + Body

                {
                    "code": "4409",
                    "description": "any description message",
                    "userMessage": "error retrieving user contacts",
                }





# Data Structures
## User
### UserLocalAuth
+ email: arbadev@gmail.com (string) - email for auth
+ password: 12345687954123456 (string) - password for auth

### UserColletion
+ password: 12345687954123456 (string) - password for auth
+ email: arbadev@gmail.com (string) - email for auth
+ firstName: andres (string) - user first name
+ lastName: barradas (string) - user last name

### ContactData
+ contact: hello@kogi.com (string) - contact email
